server-name=Bedrock Dedicated Server
gamemode=survival
force-gamemode=false
difficulty=easy
allow-cheats=false
max-players=10
online-mode=true
allow-list=false
server-port=
view-distance=8
tick-distance=4
level-name=Bedrock level
level-seed=
texturepack-required=false
